# Column Transformer 
A Column Transformer is a preprocessing utility in scikit-learn that allows you to apply different transformations to different columns of a dataset simultaneously.

## Key Idea
Real-world datasets usually contain different types of features:
- Numerical features → need scaling or normalization
- Categorical features → need encoding

Instead of preprocessing them separately, ColumnTransformer handles everything in one pipeline.

In [18]:
import numpy as np
import pandas as pd

In [19]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [20]:
df =pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day28-column-transformer/covid_toy.csv")

In [21]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [22]:
df.isnull().sum() # tio check the missing values

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [26]:
X_train

    age  gender  fever   cough       city
6    14    Male  101.0  Strong  Bangalore
77    8  Female  101.0    Mild    Kolkata
23   80  Female   98.0    Mild      Delhi
82   24    Male   98.0    Mild    Kolkata
28   16    Male  104.0    Mild    Kolkata
..  ...     ...    ...     ...        ...
5    84  Female    NaN    Mild  Bangalore
66   51    Male  104.0    Mild    Kolkata
30   15    Male  101.0    Mild      Delhi
97   20  Female  101.0    Mild  Bangalore
18   64  Female   98.0    Mild  Bangalore

[80 rows x 5 columns]

## Normal Method

In [27]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
X_train_fever.shape

(80, 1)