# Column Transformer 
A Column Transformer is a preprocessing utility in scikit-learn that allows you to apply different transformations to different columns of a dataset simultaneously.

## Key Idea
Real-world datasets usually contain different types of features:
- Numerical features → need scaling or normalization
- Categorical features → need encoding

Instead of preprocessing them separately, ColumnTransformer handles everything in one pipeline.

In [11]:
import numpy as np
import pandas as pd

In [12]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [13]:
df =pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day28-column-transformer/covid_toy.csv")

In [14]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [15]:
df.isnull().sum() # tio check the missing values

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [17]:
X_train

    age  gender  fever   cough       city
28   16    Male  104.0    Mild    Kolkata
1    27    Male  100.0    Mild      Delhi
74   34  Female  104.0  Strong      Delhi
77    8  Female  101.0    Mild    Kolkata
99   10  Female   98.0  Strong    Kolkata
..  ...     ...    ...     ...        ...
10   75  Female    NaN    Mild      Delhi
64   42    Male  104.0    Mild     Mumbai
26   19  Female  100.0    Mild    Kolkata
95   12  Female  104.0    Mild  Bangalore
35   82  Female  102.0  Strong  Bangalore

[80 rows x 5 columns]

## Normal Method

In [18]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
X_train_fever.shape

(80, 1)

In [19]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [21]:
from sklearn.preprocessing import OneHotEncoder

# create encoder
ohe = OneHotEncoder(drop='first', sparse_output=False)

# fit only on training data
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# transform test data using same encoder
X_test_gender_city = ohe.transform(X_test[['gender','city']])

# check shape
X_train_gender_city.shape

(80, 4)