# Column Transformer 
A Column Transformer is a preprocessing utility in scikit-learn that allows you to apply different transformations to different columns of a dataset simultaneously.

## Key Idea
Real-world datasets usually contain different types of features:
- Numerical features → need scaling or normalization
- Categorical features → need encoding

Instead of preprocessing them separately, ColumnTransformer handles everything in one pipeline.

In [12]:
import numpy as np
import pandas as pd

In [13]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [14]:
df =pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day28-column-transformer/covid_toy.csv")

In [15]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [18]:
df.isnull().sum() # tio check the missing values

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64