#  Student Performance Prediction using Machine Learning Pipeline

In [19]:
import numpy as np
import pandas as pd

In [20]:
df = pd.read_csv(r"D:\AI ML ENGINEERING JOURNY\03_Machine_Learning\scikit-learn\Basic of Scikit Learn\student_results.csv")
df

,StudentID,Name,Attendance,PreviousMarks,StudyHours,Participation,PassFail
0,1,Grace,84.967142,NaN,2.074098,0,1
1,2,Alice,78.617357,73.411768,1.367035,1,1
2,3,Charlie,86.476885,81.245769,0.281877,0,1
3,4,Charlie,95.230299,80.807031,4.323612,0,1
4,5,Hank,NaN,44.334959,4.064505,0,0
...,...,...,...,...,...,...,...
195,196,Ivy,83.853174,57.962365,0.906165,0,0
196,197,Frank,71.161426,39.302982,0.332481,1,0
197,198,Alice,81.537251,85.308086,3.705603,1,1
198,199,Jack,80.582087,63.281902,2.872366,0,1
199,200,Ivy,68.570297,83.567245,4.209144,0,0

### Data basic understanding
- student ID    = Rollnumber 
- attendences   = persentage (75% is safe mark )
- studyhours    = hours ()
- passfail      = 0--> fail & 1-->pass
- Participation = 0---> Not participated & 1--> Participated

### Prepare planing

In [21]:
df.isnull().sum()

StudentID         0
Name              0
Attendance       20
PreviousMarks    20
StudyHours        0
Participation     0
PassFail          0
dtype: int64

### Drop irrelevant columns
- StudentID
- Name

In [22]:
df.drop(columns=["StudentID","Name"],inplace=True) # inplace = True wil change the dataframe in this acctual place no need to save it again

In [23]:
df.head()

   Attendance  PreviousMarks  StudyHours  Participation  PassFail
0   84.967142            NaN    2.074098              0         1
1   78.617357      73.411768    1.367035              1         1
2   86.476885      81.245769    0.281877              0         1
3   95.230299      80.807031    4.323612              0         1
4         NaN      44.334959    4.064505              0         0