# Naive_Bayes

In [38]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [39]:
df = pd.read_csv("/home/ipartzix/Downloads/play_tennis.csv")

In [40]:
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [41]:
df["play"].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [42]:
# probabilit of yes and no
pYes = 9/14
pNo = 5/14

In [43]:
pd.crosstab(df["outlook"], df["play"])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [44]:
# outlook 
pon = 0
pro = 2/5
psn = 3/5

poy = 4/9
pry= 3/9
psy = 2/9

In [45]:
pd.crosstab(df["temp"], df["play"])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [46]:
# temp
pcoldNo = 1/5
photNo = 2/5
pmildNo = 2/5

pcoldYes = 3/9
photYes  = 2/9
pmildYes = 4/9

In [47]:
pd.crosstab(df["humidity"], df["play"])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [48]:
# humidity	
phighNo = 4/5
plowNo = 1/5

phighYes = 3/9
plowYes = 6/9

In [49]:
pd.crosstab(df["wind"], df["play"])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [50]:
# wind
pstrongNo = 3/5
pweakNo = 2/5

pstrongYes = 3/9
pweakYes = 6/9