# Complete Case Analysis

## 1. Definition
**Complete Case Analysis (CCA)** means:

> Only those rows (observations) that have **no missing values at all** are kept.  
> All rows with **any missing value** are removed.

---

## 2. Example

### Original Dataset

| Name | Age | Salary |
|------|-----|--------|
| A    | 25  | 50000  |
| B    | NaN | 60000  |
| C    | 30  | NaN    |
| D    | 28  | 55000  |

### After CCA

| Name | Age | Salary |
|------|-----|--------|
| A    | 25  | 50000  |
| D    | 28  | 55000  |

Rows **B** and **C** are removed because they contain missing values.

---
## 3. When to Use

- Missing data is **very small** (e.g., <5%)
- Data is **Missing Completely At Random (MCAR)**
- You want a **simple and fast method**

---

## 4. Advantages

- Simple to implement  
- No need for complex imputation  
- Keeps dataset consistent (no artificial values)  
- Works well for clean, small datasets  

---

## 5. Disadvantages

- Loss of data  
- Can introduce **bias** if data is not MCAR  
- Reduces statistical power  
- Not suitable for datasets with many missing values  

---

## 6. Assumption (Important)

CCA assumes:

- Missing values are **Missing Completely At Random (MCAR)**

If this assumption is violated, results can be misleading.

---

## 7. Python Implementation

```python
import pandas as pd

# Sample data
data = {
    'Age': [25, None, 30, 28],
    'Salary': [50000, 60000, None, 55000]
}

df = pd.DataFrame(data)

# Complete Case Analysis
df_clean = df.dropna()

print(df_clean)

In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("/home/ipartzix/AI-ML-ENGINEERING-JOURNEY/03_Machine_Learning/02_Feature_Engineering/data_science_job.csv")

In [3]:
df.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,NaN,NaN,36.0,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15.0,50-99,Pvt Ltd,47.0,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5.0,NaN,NaN,83.0,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,0.0,NaN,Pvt Ltd,52.0,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,50-99,Funded Startup,8.0,0.0

In [4]:
df.isnull().mean()*100

enrollee_id                0.000000
city                       0.000000
city_development_index     2.500261
gender                    23.530640
relevent_experience        0.000000
enrolled_university        2.014824
education_level            2.401086
major_discipline          14.683161
experience                 0.339284
company_size              30.994885
company_type              32.049274
training_hours             3.998330
target                     0.000000
dtype: float64

In [7]:
df.shape

(19158, 13)

In [9]:
cols = [var for var in df.columns if df[var].isnull().mean() < 0.05 and df[var].isnull().mean() >0]
cols

['city_development_index',
 'enrolled_university',
 'education_level',
 'experience',
 'training_hours']

In [11]:
df[cols].sample(5)

,city_development_index,enrolled_university,education_level,experience,training_hours
6320,0.624,no_enrollment,High School,11.0,82.0
10452,0.897,Full time course,Graduate,4.0,47.0
10445,0.926,no_enrollment,Graduate,9.0,92.0
15681,0.890,no_enrollment,Masters,13.0,75.0
13946,0.920,no_enrollment,Graduate,14.0,NaN

In [12]:
df['education_level'].value_counts()

education_level
Graduate          11598
Masters            4361
High School        2017
Phd                 414
Primary School      308
Name: count, dtype: int64

In [13]:
len(df[cols].dropna()) / len(df)

0.8968577095730244