# Handling missing data using mean-median imputation

In [19]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [20]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9

In [21]:
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer

In [22]:
df =pd.read_csv("/home/ipartzix/AI-ML-ENGINEERING-JOURNEY/03_Machine_Learning/02_Feature_Engineering/titanic_toy.csv")

In [23]:
df.head()

    Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1
4  35.0   8.0500       0         0

In [24]:
df.isnull().mean()

Age         0.198653
Fare        0.050505
Family      0.000000
Survived    0.000000
dtype: float64

In [25]:
X= df.drop(columns=["Survived"])
y=df[["Survived"]]

In [26]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [27]:
X_train.shape ,y_train.shape

((712, 3), (712, 1))

In [28]:
mean_age = X_train['Age'].mean()
median_age = X_train['Age'].median()

mean_fare = X_train['Fare'].mean()
median_fare = X_train['Fare'].median()

In [29]:
X_train['Age_median'] = X_train['Age'].fillna(median_age)
X_train['Age_mean'] = X_train['Age'].fillna(mean_age)

X_train['Fare_median'] = X_train['Fare'].fillna(median_fare)
X_train['Fare_mean'] = X_train['Fare'].fillna(mean_fare)

In [30]:
X_train.sample(5)

      Age     Fare  Family  Age_median   Age_mean  Fare_median  Fare_mean
392  28.0   7.9250       2       28.00  28.000000       7.9250     7.9250
559  36.0  17.4000       1       36.00  36.000000      17.4000    17.4000
102  21.0  77.2875       1       21.00  21.000000      77.2875    77.2875
841  16.0  10.5000       0       16.00  16.000000      10.5000    10.5000
674   NaN   0.0000       0       28.75  29.785904       0.0000     0.0000