In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
df = pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day38-missing-indicator/train.csv", usecols=["Age","Fare","Survived"])

In [33]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [34]:
df.isnull().mean()*100

Survived     0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [35]:
X = df.drop(columns=["Survived"])
y = df["Survived"]

In [36]:
X_train ,X_test ,y_train ,y_test =train_test_split(X,y,test_size=0.2,random_state=2)

In [37]:
X_train

      Age      Fare
30   40.0   27.7208
10    4.0   16.7000
873  47.0    9.0000
182   9.0   31.3875
876  20.0    9.8458
..    ...       ...
534  30.0    8.6625
584   NaN    8.7125
493  71.0   49.5042
527   NaN  221.7792
168   NaN   25.9250

[712 rows x 2 columns]

In [38]:
X_train["Age_imputed"] = X_train["Age"]
X_test["Age_imputed"] = X_test["Age"]

In [39]:
X_test.tail()

      Age     Fare  Age_imputed
89   24.0   8.0500         24.0
80   22.0   9.0000         22.0
846   NaN  69.5500          NaN
870  26.0   7.8958         26.0
251  29.0  10.4625         29.0

In [40]:
X_train['Age_imputed'][X_train['Age_imputed'].isnull()] = X_train['Age'].dropna().sample(X_train['Age'].isnull().sum()).values
X_test['Age_imputed'][X_test['Age_imputed'].isnull()] = X_train['Age'].dropna().sample(X_test['Age'].isnull().sum()).values

/tmp/ipykernel_68200/3090101260.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  X_train['Age_imputed'][X_train['Age_imputed'].isnull()] = X_train['Age'].dropna().sample(X_train['Age'].isnull().sum()).values
/tmp/ipykernel_68200/3090101260.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  X_test['Age_imputed'][X_test['Age_imputed'].isnull()] = X_train['Age'].dropna().sample(X_test['Age'].isnull().sum()).values

In [41]:
X_train['Age'].dropna().sample(X_train['Age'].isnull().sum()).values

array([16.  , 40.5 , 21.  , 58.  , 24.  , 32.  , 28.  , 58.  , 22.  ,
       19.  , 50.  , 27.  , 38.  ,  1.  , 35.  , 32.  , 30.  , 19.  ,
       26.  , 36.  ,  1.  , 16.  , 23.5 , 45.  , 16.  , 64.  , 36.  ,
       19.  , 21.  , 38.  , 34.  , 28.  , 19.  , 40.  , 21.  , 16.  ,
        9.  , 26.  , 36.  ,  0.67, 18.  , 29.  , 26.  ,  2.  , 35.  ,
       23.  , 29.  , 19.  , 28.  , 30.  , 45.  , 37.  , 22.  , 50.  ,
       31.  , 33.  , 32.  , 51.  , 11.  , 28.5 , 48.  , 22.  , 39.  ,
       42.  , 41.  , 42.  , 25.  , 14.  , 52.  , 31.  , 40.  , 47.  ,
        7.  , 27.  , 47.  , 44.  , 46.  , 28.  , 32.  , 20.  ,  3.  ,
       45.  ,  6.  , 35.  , 24.  , 20.  , 28.  , 22.  , 28.  ,  9.  ,
       40.  , 30.  , 52.  , 48.  , 23.  ,  2.  , 51.  , 35.  , 17.  ,
       43.  , 33.  , 54.  , 14.5 , 28.  , 65.  , 32.  , 65.  , 27.  ,
       40.  , 49.  , 27.  , 18.  , 19.  , 27.  , 12.  , 24.  , 24.  ,
       24.  , 18.  , 22.  , 19.  , 40.  , 15.  , 34.  ,  0.75, 26.  ,
       26.  , 45.5 , 50.  ,  2.  , 19.  , 51.  , 45.  ,  8.  ,  8.  ,
       29.  , 56.  , 47.  , 26.  , 29.  , 25.  , 28.  ,  4.  , 21.  ,
       33.  , 36.  , 22.  , 22.  ])

In [42]:
X_train['Age'].isnull().sum()

np.int64(148)

In [43]:
X_train

      Age      Fare  Age_imputed
30   40.0   27.7208         40.0
10    4.0   16.7000          4.0
873  47.0    9.0000         47.0
182   9.0   31.3875          9.0
876  20.0    9.8458         20.0
..    ...       ...          ...
534  30.0    8.6625         30.0
584   NaN    8.7125          NaN
493  71.0   49.5042         71.0
527   NaN  221.7792          NaN
168   NaN   25.9250          NaN

[712 rows x 3 columns]