In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv('/home/ipartzix/ML-dataset/IMDB Dataset.csv')

In [9]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [10]:
df.describe

<bound method NDFrame.describe of                                                   review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]>

In [14]:
df ["review"][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

## Text data cleaning 
1. Sample 10000 rows 
2. Remove html tags 
3. Remove special characters 
4. Converting every thing to lower case 
5. Removing stop words 
6. Stamming

In [15]:
df= df.sample(10000)

In [19]:
df.info

<bound method DataFrame.info of                                                   review sentiment
32397  From beginning to end, this is the most emotio...  negative
36782  I rented it because the second segment traumat...  negative
15988  The Young Victoria is a beautiful film and has...  positive
32411  Nightbreed blew my mind the first time I saw i...  positive
26182  I saw this on Zone horror and fully expected i...  positive
...                                                  ...       ...
34553  the intention the directors has for this films...  negative
14569  When my own child is begging me to leave the o...  negative
24979  Whereas the movie was beautifully shot and rea...  negative
4358   This was the worst acted movie I've ever seen ...  negative
41179  A gem of a cartoon from the silent era---it wa...  positive

[10000 rows x 2 columns]>

In [21]:
# df['sentiment'].replace({"positive": 1 , "negative":0},inplace= True)  # it may automatic downcasting

df['sentiment'] = df['sentiment'].replace({
    "positive": 1,
    "negative": 0
})
# the second version is the recommended modern Pandas style.

In [22]:
df.head()

                                                  review  sentiment
32397  From beginning to end, this is the most emotio...          0
36782  I rented it because the second segment traumat...          0
15988  The Young Victoria is a beautiful film and has...          1
32411  Nightbreed blew my mind the first time I saw i...          1
26182  I saw this on Zone horror and fully expected i...          1